### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by maodow** [xfhy/DeepNight-in-kotlin#2]
java.lang.NullPointerException
                                                                        at com.xfhy.deepnight.fragment.CommonMainFragment$doNetwork$1.onSuccess(CommonMainFragment.kt:90)
                                                                        at com.xfhy.deepnight.net.NetUtils$reqOutList$1$3.invoke(NetUtils.kt:69)
                                                                        at com.xfhy.deepnight.net.NetUtils$reqOutList$1$3.invoke(NetUtils.kt:17)
                                                                        at org.jetbrains.anko.AsyncKt$uiThread$1.run(Async.kt:70)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by maodow** [comment]
刚打开，崩溃

**Comment by xfhy** [comment]
兄弟,如何复现的呢?
```kotlin
fun reqOutList(url: String, index: Int, response: ZResponse) {
        doAsync {
                ......
                uiThread {
                    response.onSuccess(outLists)
                }
            } catch (e: Exception) {
                uiThread {
                    response.onError(e.message)
                }
            }
        }
    }
```
我才疏学浅,没有发现问题..哥们有什么解决办法吗?这里的response不可能为null啊,好奇怪
